In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
df=pd.read_csv("Flipkart_Sample_Data.csv")

In [4]:
df

,uniq_id,crawl_timestamp,product_url,product_name,product_category_tree,pid,retail_price_₹,discounted_price_₹,Selling Price ₹,Discount %,image,is_FK_Advantage_product,product_rating,overall_rating,brand,description,product_specifications
0,c2d766ca982eca8304150849735ffef9,2016-03-25 22:59:23 +0000,http://www.flipkart.com/alisha-solid-women-s-c...,Alisha Solid Women's Cycling Shorts,"[""Clothing >> Women's Clothing >> Lingerie, Sl...",SRTEH2FF9KEDEFGF,999.0,379.0,937.0,62.0,"[""http://img5a.flixcart.com/image/short/u/4/a/...",False,NaN,NaN,Alisha,Key Features of Alisha Solid Women's Cycling S...,"{""product_specification""=>[{""key""=>""Number of ..."
1,7f7036a6d550aaa89d34c77bd39a5e48,2016-03-25 22:59:23 +0000,http://www.flipkart.com/fabhomedecor-fabric-do...,FabHomeDecor Fabric Double Sofa Bed,"[""Furniture >> Living Room Furniture >> Sofa B...",SBEEH3QGU7MFYJFY,32157.0,22646.0,32127.0,30.0,"[""http://img6a.flixcart.com/image/sofa-bed/j/f...",False,NaN,NaN,FabHomeDecor,FabHomeDecor Fabric Double Sofa Bed (Finish Co...,"{""product_specification""=>[{""key""=>""Installati..."
2,f449ec65dcbc041b6ae5e6a32717d01b,2016-03-25 22:59:23 +0000,http://www.flipkart.com/aw-bellies/p/itmeh4grg...,AW Bellies,"[""Footwear >> Women's Footwear >> Ballerinas >...",SHOEH4GRSUBJGZXE,999.0,499.0,949.0,50.0,"[""http://img5a.flixcart.com/image/shoe/7/z/z/r...",False,NaN,NaN,AW,Key Features of AW Bellies Sandals Wedges Heel...,"{""product_specification""=>[{""key""=>""Ideal For""..."
3,0973b37acd0c664e3de26e97e5571454,2016-03-25 22:59:23 +0000,http://www.flipkart.com/alisha-solid-women-s-c...,Alisha Solid Women's Cycling Shorts,"[""Clothing >> Women's Clothing >> Lingerie, Sl...",SRTEH2F6HUZMQ6SJ,699.0,267.0,637.0,62.0,"[""http://img5a.flixcart.com/image/short/6/2/h/...",False,NaN,NaN,Alisha,Key Features of Alisha Solid Women's Cycling S...,"{""product_specification""=>[{""key""=>""Number of ..."
4,bc940ea42ee6bef5ac7cea3fb5cfbee7,2016-03-25 22:59:23 +0000,http://www.flipkart.com/sicons-all-purpose-arn...,Sicons All Purpose Arnica Dog Shampoo,"[""Pet Supplies >> Grooming >> Skin & Coat Care...",PSOEH3ZYDMSYARJ5,220.0,210.0,215.0,5.0,"[""http://img5a.flixcart.com/image/pet-shampoo/...",False,NaN,NaN,Sicons,Specifications of Sicons All Purpose Arnica Do...,"{""product_specification""=>[{""key""=>""Pet Type"",..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,7179d2f6c4ad50a17d014ca1d2815156,2015-12-01 10:15:43 +0000,http://www.flipkart.com/walldesign-small-vinyl...,WallDesign Small Vinyl Sticker,"[""Baby Care >> Baby & Kids Gifts >> Stickers >...",STIE7KFJAKSTDY9G,1500.0,730.0,1449.0,51.0,"[""http://img6a.flixcart.com/image/wall-decorat...",False,NaN,NaN,WallDesign,Buy WallDesign Small Vinyl Sticker for Rs.730 ...,"{""product_specification""=>[{""key""=>""Number of ..."
19996,71ac419198359d37b8fe5e3fffdfee09,2015-12-01 10:15:43 +0000,http://www.flipkart.com/wallmantra-large-vinyl...,Wallmantra Large Vinyl Stickers Sticker,"[""Baby Care >> Baby & Kids Gifts >> Stickers >...",STIE9F5URNQGJCGH,1429.0,1143.0,1409.0,20.0,"[""http://img6a.flixcart.com/image/sticker/z/g/...",False,NaN,NaN,Wallmantra,Buy Wallmantra Large Vinyl Stickers Sticker fo...,"{""product_specification""=>[{""key""=>""Number of ..."
19997,93e9d343837400ce0d7980874ece471c,2015-12-01 10:15:43 +0000,http://www.flipkart.com/elite-collection-mediu...,Elite Collection Medium Acrylic Sticker,"[""Baby Care >> Baby & Kids Gifts >> Stickers >...",STIE7VAYDKQZEBSD,1299.0,999.0,1276.0,23.0,"[""http://img5a.flixcart.com/image/sticker/b/s/...",False,NaN,NaN,Elite Collection,Buy Elite Collection Medium Acrylic Sticker fo...,"{""product_specification""=>[{""key""=>""Number of ..."
19998,669e79b8fa5d9ae020841c0c97d5e935,2015-12-01 10:15:43 +0000,http://www.flipkart.com/elite-collection-mediu...,Elite Collection Medium Acrylic Sticker,"[""Baby Care >> Baby & Kids Gifts >> Stickers >...",STIE8YSVEPPCZ42Y,1499.0,1199.0,1479.0,20.0,"[""http://img5a.flixcart.com/image/sticker/4/2/...",False,NaN,NaN,Elite Collection,Buy Elite Collection Medium Acrylic Sticker fo...,"{""product_specification""=>[{""key""=>""Number of ..."
19999,cb4fa87a874f715fff567f7b7b3be79c,2015-12-01 10:15:43 +0000,http://www.flipkart.com/elite-collection-mediu...,Elite Collection Medium Acrylic Sticker,"[""Baby Care >> Baby & Kids Gifts >> Stickers >...",STIE88KN9ZDSGZKY,1499.0,999.0,1466.0,33.0,"[""http://img6a.flixcart.com/image/sticker/z/k/...",False,NaN,NaN,Elite Collection,Buy Elite Collection Medium Acrylic Sticker fo...,"{""product_specification""=>[{""key""=>""Number of ..."

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 17 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   uniq_id                  20000 non-null  str
 1   crawl_timestamp          20000 non-null  str
 2   product_url              20000 non-null  str
 3   product_name             20000 non-null  str
 4   product_category_tree    20000 non-null  str
 5   pid                      20000 non-null  str
 6   retail_price_₹           19922 non-null  float64
 7   discounted_price_₹       19922 non-null  float64
 8   Selling Price ₹          19922 non-null  float64
 9   Discount %               19922 non-null  float64
 10  image                    19997 non-null  str
 11  is_FK_Advantage_product  20000 non-null  bool
 12  product_rating           1849 non-null   float64
 13  overall_rating           1849 non-null   float64
 14  brand                    14136 non-null  str
 15  description              19998 non-null  str
 16  product_specifications   19986 non-null  str
dtypes: bool(1), float64(6), str(10)
memory usage: 2.5 MB

In [6]:
df.shape

(20000, 17)

In [7]:
df.isnull().sum()

uniq_id                        0
crawl_timestamp                0
product_url                    0
product_name                   0
product_category_tree          0
pid                            0
retail_price_₹                78
discounted_price_₹            78
Selling Price ₹               78
Discount %                    78
image                          3
is_FK_Advantage_product        0
product_rating             18151
overall_rating             18151
brand                       5864
description                    2
product_specifications        14
dtype: int64

In [8]:
df["Main_Category"] = (
    df["product_category_tree"]
    .str.extract(r'\["([^>]*)')
)

In [9]:
df["Main_Category"].value_counts()

Main_Category
Clothing                                                 6198
Jewellery                                                3531
Footwear                                                 1227
Mobiles & Accessories                                    1099
Automotive                                               1012
                                                         ...
Speedwav 186926 Royal Enfield 350 Twin Spark LED..."]       1
Speedwav 186879 Bajaj Pulsar 200 NS DTS-i LED In..."]       1
Pazel Slim Fit Men's Jeans"]                                1
SMART TRADERS Girls Bellies"]                               1
Areon Luxurious Fragrance Long Lasting Car,Home,..."]       1
Name: count, Length: 266, dtype: int64

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 18 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   uniq_id                  20000 non-null  str
 1   crawl_timestamp          20000 non-null  str
 2   product_url              20000 non-null  str
 3   product_name             20000 non-null  str
 4   product_category_tree    20000 non-null  str
 5   pid                      20000 non-null  str
 6   retail_price_₹           19922 non-null  float64
 7   discounted_price_₹       19922 non-null  float64
 8   Selling Price ₹          19922 non-null  float64
 9   Discount %               19922 non-null  float64
 10  image                    19997 non-null  str
 11  is_FK_Advantage_product  20000 non-null  bool
 12  product_rating           1849 non-null   float64
 13  overall_rating           1849 non-null   float64
 14  brand                    14136 non-null  str
 15  description              19998 non-null  str
 16  product_specifications   19986 non-null  str
 17  Main_Category            20000 non-null  str
dtypes: bool(1), float64(6), str(11)
memory usage: 2.6 MB

In [11]:
df.duplicated().sum()

np.int64(0)

In [12]:
df.isnull().sum()

uniq_id                        0
crawl_timestamp                0
product_url                    0
product_name                   0
product_category_tree          0
pid                            0
retail_price_₹                78
discounted_price_₹            78
Selling Price ₹               78
Discount %                    78
image                          3
is_FK_Advantage_product        0
product_rating             18151
overall_rating             18151
brand                       5864
description                    2
product_specifications        14
Main_Category                  0
dtype: int64

In [13]:
df.drop(columns=['product_rating'])

,uniq_id,crawl_timestamp,product_url,product_name,product_category_tree,pid,retail_price_₹,discounted_price_₹,Selling Price ₹,Discount %,image,is_FK_Advantage_product,overall_rating,brand,description,product_specifications,Main_Category
0,c2d766ca982eca8304150849735ffef9,2016-03-25 22:59:23 +0000,http://www.flipkart.com/alisha-solid-women-s-c...,Alisha Solid Women's Cycling Shorts,"[""Clothing >> Women's Clothing >> Lingerie, Sl...",SRTEH2FF9KEDEFGF,999.0,379.0,937.0,62.0,"[""http://img5a.flixcart.com/image/short/u/4/a/...",False,NaN,Alisha,Key Features of Alisha Solid Women's Cycling S...,"{""product_specification""=>[{""key""=>""Number of ...",Clothing
1,7f7036a6d550aaa89d34c77bd39a5e48,2016-03-25 22:59:23 +0000,http://www.flipkart.com/fabhomedecor-fabric-do...,FabHomeDecor Fabric Double Sofa Bed,"[""Furniture >> Living Room Furniture >> Sofa B...",SBEEH3QGU7MFYJFY,32157.0,22646.0,32127.0,30.0,"[""http://img6a.flixcart.com/image/sofa-bed/j/f...",False,NaN,FabHomeDecor,FabHomeDecor Fabric Double Sofa Bed (Finish Co...,"{""product_specification""=>[{""key""=>""Installati...",Furniture
2,f449ec65dcbc041b6ae5e6a32717d01b,2016-03-25 22:59:23 +0000,http://www.flipkart.com/aw-bellies/p/itmeh4grg...,AW Bellies,"[""Footwear >> Women's Footwear >> Ballerinas >...",SHOEH4GRSUBJGZXE,999.0,499.0,949.0,50.0,"[""http://img5a.flixcart.com/image/shoe/7/z/z/r...",False,NaN,AW,Key Features of AW Bellies Sandals Wedges Heel...,"{""product_specification""=>[{""key""=>""Ideal For""...",Footwear
3,0973b37acd0c664e3de26e97e5571454,2016-03-25 22:59:23 +0000,http://www.flipkart.com/alisha-solid-women-s-c...,Alisha Solid Women's Cycling Shorts,"[""Clothing >> Women's Clothing >> Lingerie, Sl...",SRTEH2F6HUZMQ6SJ,699.0,267.0,637.0,62.0,"[""http://img5a.flixcart.com/image/short/6/2/h/...",False,NaN,Alisha,Key Features of Alisha Solid Women's Cycling S...,"{""product_specification""=>[{""key""=>""Number of ...",Clothing
4,bc940ea42ee6bef5ac7cea3fb5cfbee7,2016-03-25 22:59:23 +0000,http://www.flipkart.com/sicons-all-purpose-arn...,Sicons All Purpose Arnica Dog Shampoo,"[""Pet Supplies >> Grooming >> Skin & Coat Care...",PSOEH3ZYDMSYARJ5,220.0,210.0,215.0,5.0,"[""http://img5a.flixcart.com/image/pet-shampoo/...",False,NaN,Sicons,Specifications of Sicons All Purpose Arnica Do...,"{""product_specification""=>[{""key""=>""Pet Type"",...",Pet Supplies
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,7179d2f6c4ad50a17d014ca1d2815156,2015-12-01 10:15:43 +0000,http://www.flipkart.com/walldesign-small-vinyl...,WallDesign Small Vinyl Sticker,"[""Baby Care >> Baby & Kids Gifts >> Stickers >...",STIE7KFJAKSTDY9G,1500.0,730.0,1449.0,51.0,"[""http://img6a.flixcart.com/image/wall-decorat...",False,NaN,WallDesign,Buy WallDesign Small Vinyl Sticker for Rs.730 ...,"{""product_specification""=>[{""key""=>""Number of ...",Baby Care
19996,71ac419198359d37b8fe5e3fffdfee09,2015-12-01 10:15:43 +0000,http://www.flipkart.com/wallmantra-large-vinyl...,Wallmantra Large Vinyl Stickers Sticker,"[""Baby Care >> Baby & Kids Gifts >> Stickers >...",STIE9F5URNQGJCGH,1429.0,1143.0,1409.0,20.0,"[""http://img6a.flixcart.com/image/sticker/z/g/...",False,NaN,Wallmantra,Buy Wallmantra Large Vinyl Stickers Sticker fo...,"{""product_specification""=>[{""key""=>""Number of ...",Baby Care
19997,93e9d343837400ce0d7980874ece471c,2015-12-01 10:15:43 +0000,http://www.flipkart.com/elite-collection-mediu...,Elite Collection Medium Acrylic Sticker,"[""Baby Care >> Baby & Kids Gifts >> Stickers >...",STIE7VAYDKQZEBSD,1299.0,999.0,1276.0,23.0,"[""http://img5a.flixcart.com/image/sticker/b/s/...",False,NaN,Elite Collection,Buy Elite Collection Medium Acrylic Sticker fo...,"{""product_specification""=>[{""key""=>""Number of ...",Baby Care
19998,669e79b8fa5d9ae020841c0c97d5e935,2015-12-01 10:15:43 +0000,http://www.flipkart.com/elite-collection-mediu...,Elite Collection Medium Acrylic Sticker,"[""Baby Care >> Baby & Kids Gifts >> Stickers >...",STIE8YSVEPPCZ42Y,1499.0,1199.0,1479.0,20.0,"[""http://img5a.flixcart.com/image/sticker/4/2/...",False,NaN,Elite Collection,Buy Elite Collection Medium Acrylic Sticker fo...,"{""product_specification""=>[{""key""=>""Number of ...",Baby Care
19999,cb4fa87a874f715fff567f7b7b3be79c,2015-12-01 10:15:43 +0000,http://www.flipkart.com/elite-collection-mediu...,Elite Collection Medium Acrylic Sticker,"[""Baby Care >> Baby & Kids Gifts >> Stickers >...",STIE88KN9ZDSGZKY,1499.0,999.0,1466.0,33.0,"[""http://img6a.flixcart.com/image/sticker/z/k/...",False,NaN,Elite Collection,Buy Elite Collection Medium Acrylic Sticker fo...,"{""product_specification""=>[{""key""=>""Number of ...",Baby Care

In [14]:
df.drop(columns=['overall_rating'])

,uniq_id,crawl_timestamp,product_url,product_name,product_category_tree,pid,retail_price_₹,discounted_price_₹,Selling Price ₹,Discount %,image,is_FK_Advantage_product,product_rating,brand,description,product_specifications,Main_Category
0,c2d766ca982eca8304150849735ffef9,2016-03-25 22:59:23 +0000,http://www.flipkart.com/alisha-solid-women-s-c...,Alisha Solid Women's Cycling Shorts,"[""Clothing >> Women's Clothing >> Lingerie, Sl...",SRTEH2FF9KEDEFGF,999.0,379.0,937.0,62.0,"[""http://img5a.flixcart.com/image/short/u/4/a/...",False,NaN,Alisha,Key Features of Alisha Solid Women's Cycling S...,"{""product_specification""=>[{""key""=>""Number of ...",Clothing
1,7f7036a6d550aaa89d34c77bd39a5e48,2016-03-25 22:59:23 +0000,http://www.flipkart.com/fabhomedecor-fabric-do...,FabHomeDecor Fabric Double Sofa Bed,"[""Furniture >> Living Room Furniture >> Sofa B...",SBEEH3QGU7MFYJFY,32157.0,22646.0,32127.0,30.0,"[""http://img6a.flixcart.com/image/sofa-bed/j/f...",False,NaN,FabHomeDecor,FabHomeDecor Fabric Double Sofa Bed (Finish Co...,"{""product_specification""=>[{""key""=>""Installati...",Furniture
2,f449ec65dcbc041b6ae5e6a32717d01b,2016-03-25 22:59:23 +0000,http://www.flipkart.com/aw-bellies/p/itmeh4grg...,AW Bellies,"[""Footwear >> Women's Footwear >> Ballerinas >...",SHOEH4GRSUBJGZXE,999.0,499.0,949.0,50.0,"[""http://img5a.flixcart.com/image/shoe/7/z/z/r...",False,NaN,AW,Key Features of AW Bellies Sandals Wedges Heel...,"{""product_specification""=>[{""key""=>""Ideal For""...",Footwear
3,0973b37acd0c664e3de26e97e5571454,2016-03-25 22:59:23 +0000,http://www.flipkart.com/alisha-solid-women-s-c...,Alisha Solid Women's Cycling Shorts,"[""Clothing >> Women's Clothing >> Lingerie, Sl...",SRTEH2F6HUZMQ6SJ,699.0,267.0,637.0,62.0,"[""http://img5a.flixcart.com/image/short/6/2/h/...",False,NaN,Alisha,Key Features of Alisha Solid Women's Cycling S...,"{""product_specification""=>[{""key""=>""Number of ...",Clothing
4,bc940ea42ee6bef5ac7cea3fb5cfbee7,2016-03-25 22:59:23 +0000,http://www.flipkart.com/sicons-all-purpose-arn...,Sicons All Purpose Arnica Dog Shampoo,"[""Pet Supplies >> Grooming >> Skin & Coat Care...",PSOEH3ZYDMSYARJ5,220.0,210.0,215.0,5.0,"[""http://img5a.flixcart.com/image/pet-shampoo/...",False,NaN,Sicons,Specifications of Sicons All Purpose Arnica Do...,"{""product_specification""=>[{""key""=>""Pet Type"",...",Pet Supplies
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,7179d2f6c4ad50a17d014ca1d2815156,2015-12-01 10:15:43 +0000,http://www.flipkart.com/walldesign-small-vinyl...,WallDesign Small Vinyl Sticker,"[""Baby Care >> Baby & Kids Gifts >> Stickers >...",STIE7KFJAKSTDY9G,1500.0,730.0,1449.0,51.0,"[""http://img6a.flixcart.com/image/wall-decorat...",False,NaN,WallDesign,Buy WallDesign Small Vinyl Sticker for Rs.730 ...,"{""product_specification""=>[{""key""=>""Number of ...",Baby Care
19996,71ac419198359d37b8fe5e3fffdfee09,2015-12-01 10:15:43 +0000,http://www.flipkart.com/wallmantra-large-vinyl...,Wallmantra Large Vinyl Stickers Sticker,"[""Baby Care >> Baby & Kids Gifts >> Stickers >...",STIE9F5URNQGJCGH,1429.0,1143.0,1409.0,20.0,"[""http://img6a.flixcart.com/image/sticker/z/g/...",False,NaN,Wallmantra,Buy Wallmantra Large Vinyl Stickers Sticker fo...,"{""product_specification""=>[{""key""=>""Number of ...",Baby Care
19997,93e9d343837400ce0d7980874ece471c,2015-12-01 10:15:43 +0000,http://www.flipkart.com/elite-collection-mediu...,Elite Collection Medium Acrylic Sticker,"[""Baby Care >> Baby & Kids Gifts >> Stickers >...",STIE7VAYDKQZEBSD,1299.0,999.0,1276.0,23.0,"[""http://img5a.flixcart.com/image/sticker/b/s/...",False,NaN,Elite Collection,Buy Elite Collection Medium Acrylic Sticker fo...,"{""product_specification""=>[{""key""=>""Number of ...",Baby Care
19998,669e79b8fa5d9ae020841c0c97d5e935,2015-12-01 10:15:43 +0000,http://www.flipkart.com/elite-collection-mediu...,Elite Collection Medium Acrylic Sticker,"[""Baby Care >> Baby & Kids Gifts >> Stickers >...",STIE8YSVEPPCZ42Y,1499.0,1199.0,1479.0,20.0,"[""http://img5a.flixcart.com/image/sticker/4/2/...",False,NaN,Elite Collection,Buy Elite Collection Medium Acrylic Sticker fo...,"{""product_specification""=>[{""key""=>""Number of ...",Baby Care
19999,cb4fa87a874f715fff567f7b7b3be79c,2015-12-01 10:15:43 +0000,http://www.flipkart.com/elite-collection-mediu...,Elite Collection Medium Acrylic Sticker,"[""Baby Care >> Baby & Kids Gifts >> Stickers >...",STIE88KN9ZDSGZKY,1499.0,999.0,1466.0,33.0,"[""http://img6a.flixcart.com/image/sticker/z/k/...",False,NaN,Elite Collection,Buy Elite Collection Medium Acrylic Sticker fo...,"{""product_specification""=>[{""key""=>""Number of ...",Baby Care

In [15]:
df["brand"]=df["brand"].fillna("unknown")

In [16]:
df.isnull().sum()

uniq_id                        0
crawl_timestamp                0
product_url                    0
product_name                   0
product_category_tree          0
pid                            0
retail_price_₹                78
discounted_price_₹            78
Selling Price ₹               78
Discount %                    78
image                          3
is_FK_Advantage_product        0
product_rating             18151
overall_rating             18151
brand                          0
description                    2
product_specifications        14
Main_Category                  0
dtype: int64

In [17]:
df.drop(
    columns=['product_rating',
             'overall_rating',
             'image'],
    inplace=True
)

In [18]:
df["description"]=df["description"].fillna("Not_Available")

In [19]:
df['product_specifications'] = (
    df['product_specifications']
    .fillna('Not Available')
)

In [20]:
df.isnull().sum()

uniq_id                     0
crawl_timestamp             0
product_url                 0
product_name                0
product_category_tree       0
pid                         0
retail_price_₹             78
discounted_price_₹         78
Selling Price ₹            78
Discount %                 78
is_FK_Advantage_product     0
brand                       0
description                 0
product_specifications      0
Main_Category               0
dtype: int64

In [21]:
df = df.dropna(
    subset=['retail_price_₹',
            'discounted_price_₹',
           'Selling Price ₹',
           'Discount %']
)

In [22]:
# price Segement

In [23]:
def price_segment(price):
    if price < 500:
        return 'Budget'
    elif price < 2000:
        return 'Mid-Range'
    else:
        return 'Premium'

In [24]:
df['Price_Segment'] = (
    df['discounted_price_₹']
    .apply(price_segment)
)

In [25]:
df.head(4)

,uniq_id,crawl_timestamp,product_url,product_name,product_category_tree,pid,retail_price_₹,discounted_price_₹,Selling Price ₹,Discount %,is_FK_Advantage_product,brand,description,product_specifications,Main_Category,Price_Segment
0,c2d766ca982eca8304150849735ffef9,2016-03-25 22:59:23 +0000,http://www.flipkart.com/alisha-solid-women-s-c...,Alisha Solid Women's Cycling Shorts,"[""Clothing >> Women's Clothing >> Lingerie, Sl...",SRTEH2FF9KEDEFGF,999.0,379.0,937.0,62.0,False,Alisha,Key Features of Alisha Solid Women's Cycling S...,"{""product_specification""=>[{""key""=>""Number of ...",Clothing,Budget
1,7f7036a6d550aaa89d34c77bd39a5e48,2016-03-25 22:59:23 +0000,http://www.flipkart.com/fabhomedecor-fabric-do...,FabHomeDecor Fabric Double Sofa Bed,"[""Furniture >> Living Room Furniture >> Sofa B...",SBEEH3QGU7MFYJFY,32157.0,22646.0,32127.0,30.0,False,FabHomeDecor,FabHomeDecor Fabric Double Sofa Bed (Finish Co...,"{""product_specification""=>[{""key""=>""Installati...",Furniture,Premium
2,f449ec65dcbc041b6ae5e6a32717d01b,2016-03-25 22:59:23 +0000,http://www.flipkart.com/aw-bellies/p/itmeh4grg...,AW Bellies,"[""Footwear >> Women's Footwear >> Ballerinas >...",SHOEH4GRSUBJGZXE,999.0,499.0,949.0,50.0,False,AW,Key Features of AW Bellies Sandals Wedges Heel...,"{""product_specification""=>[{""key""=>""Ideal For""...",Footwear,Budget
3,0973b37acd0c664e3de26e97e5571454,2016-03-25 22:59:23 +0000,http://www.flipkart.com/alisha-solid-women-s-c...,Alisha Solid Women's Cycling Shorts,"[""Clothing >> Women's Clothing >> Lingerie, Sl...",SRTEH2F6HUZMQ6SJ,699.0,267.0,637.0,62.0,False,Alisha,Key Features of Alisha Solid Women's Cycling S...,"{""product_specification""=>[{""key""=>""Number of ...",Clothing,Budget

In [26]:
df.info()

<class 'pandas.DataFrame'>
Index: 19922 entries, 0 to 19999
Data columns (total 16 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   uniq_id                  19922 non-null  str
 1   crawl_timestamp          19922 non-null  str
 2   product_url              19922 non-null  str
 3   product_name             19922 non-null  str
 4   product_category_tree    19922 non-null  str
 5   pid                      19922 non-null  str
 6   retail_price_₹           19922 non-null  float64
 7   discounted_price_₹       19922 non-null  float64
 8   Selling Price ₹          19922 non-null  float64
 9   Discount %               19922 non-null  float64
 10  is_FK_Advantage_product  19922 non-null  bool
 11  brand                    19922 non-null  str
 12  description              19922 non-null  str
 13  product_specifications   19922 non-null  str
 14  Main_Category            19922 non-null  str
 15  Price_Segment            19922 non-null  str
dtypes: bool(1), float64(4), str(11)
memory usage: 2.5 MB

In [27]:
df['Discount_Amount'] = (
    df['retail_price_₹']
    - df['discounted_price_₹']
)

In [28]:
df.head(3)

,uniq_id,crawl_timestamp,product_url,product_name,product_category_tree,pid,retail_price_₹,discounted_price_₹,Selling Price ₹,Discount %,is_FK_Advantage_product,brand,description,product_specifications,Main_Category,Price_Segment,Discount_Amount
0,c2d766ca982eca8304150849735ffef9,2016-03-25 22:59:23 +0000,http://www.flipkart.com/alisha-solid-women-s-c...,Alisha Solid Women's Cycling Shorts,"[""Clothing >> Women's Clothing >> Lingerie, Sl...",SRTEH2FF9KEDEFGF,999.0,379.0,937.0,62.0,False,Alisha,Key Features of Alisha Solid Women's Cycling S...,"{""product_specification""=>[{""key""=>""Number of ...",Clothing,Budget,620.0
1,7f7036a6d550aaa89d34c77bd39a5e48,2016-03-25 22:59:23 +0000,http://www.flipkart.com/fabhomedecor-fabric-do...,FabHomeDecor Fabric Double Sofa Bed,"[""Furniture >> Living Room Furniture >> Sofa B...",SBEEH3QGU7MFYJFY,32157.0,22646.0,32127.0,30.0,False,FabHomeDecor,FabHomeDecor Fabric Double Sofa Bed (Finish Co...,"{""product_specification""=>[{""key""=>""Installati...",Furniture,Premium,9511.0
2,f449ec65dcbc041b6ae5e6a32717d01b,2016-03-25 22:59:23 +0000,http://www.flipkart.com/aw-bellies/p/itmeh4grg...,AW Bellies,"[""Footwear >> Women's Footwear >> Ballerinas >...",SHOEH4GRSUBJGZXE,999.0,499.0,949.0,50.0,False,AW,Key Features of AW Bellies Sandals Wedges Heel...,"{""product_specification""=>[{""key""=>""Ideal For""...",Footwear,Budget,500.0

In [29]:
df['Discount_Percentage'] = (
    df['Discount_Amount']
    / df['retail_price_₹']
) * 100

In [30]:
df.columns

Index(['uniq_id', 'crawl_timestamp', 'product_url', 'product_name',
       'product_category_tree', 'pid', 'retail_price_₹', 'discounted_price_₹',
       'Selling Price ₹', 'Discount %', 'is_FK_Advantage_product', 'brand',
       'description', 'product_specifications', 'Main_Category',
       'Price_Segment', 'Discount_Amount', 'Discount_Percentage'],
      dtype='str')

In [31]:
df.Main_Category.value_counts().head(20)

Main_Category
Clothing                       6171
Jewellery                      3522
Footwear                       1225
Mobiles & Accessories          1097
Automotive                     1010
Home Decor & Festive Needs      927
Beauty and Personal Care        709
Home Furnishing                 700
Kitchen & Dining                645
Computers                       573
Watches                         528
Baby Care                       481
Tools & Hardware                387
Toys & School Supplies          329
Pens & Stationery               313
Bags, Wallets & Belts           264
Furniture                       180
Sports & Fitness                166
Home Improvement                 79
Cameras & Accessories            72
Name: count, dtype: int64

In [32]:
df['discounted_price_₹'].describe()

count     19922.000000
mean       1973.401767
std        7333.586040
min          35.000000
25%         350.000000
50%         550.000000
75%         999.000000
max      571230.000000
Name: discounted_price_₹, dtype: float64

In [33]:
df.nlargest(10, 'discounted_price_₹')[
    ['product_name', 'brand', 'Main_Category', 'discounted_price_₹']
]

,product_name,brand,Main_Category,discounted_price_₹
116,Breitling AB011010/BB08 131S Chronomat 44 Anal...,unknown,Watches,571230.0
134,"Cartier W6701005 Analog Watch - For Boys, Men",unknown,Watches,201000.0
11631,Durian Leather 2 Seater Sofa,Durian,Furniture,162825.0
11507,Durian Laze/3 Leather 3 Seater Sofa,Durian,Furniture,141375.0
11464,Durian Leather 2 Seater Sofa,Durian,Furniture,132990.0
7915,"Audeze Lcd2 In Bamboo, High Quality Planar Mag...",Audeze,Mobiles & Accessories,116292.0
108,TAG Heuer CAU1116.BA0858 Formula 1 Analog Watc...,unknown,Watches,107750.0
11327,Durian Club/3 Leather 3 Seater Sofa,Durian,Furniture,105300.0
11504,ARRA Solid Wood 7 Seater Sofa,ARRA,Furniture,86500.0
11576,Durian Helena Fabric 3 Seater Sofa,Durian,Furniture,70785.0

In [34]:
df['Price_Segment'].value_counts()

Price_Segment
Budget       9385
Mid-Range    8633
Premium      1904
Name: count, dtype: int64

In [35]:
df.groupby('Main_Category')['discounted_price_₹'] \
  .mean() \
  .sort_values(ascending=False) \
  .head(10)

Main_Category
Furniture                                             17114.472222
Automation & Robotics                                 17000.000000
Asics Gel-Kayano 22 Running Shoes"]                   12499.000000
Rasav Jewels Yellow Gold Diamond 18 K Ring"]           9733.000000
Asics Gel-Cumulus 17 Running Shoes"]                   9499.000000
BALAJI EXPORTS Bottled Wine Cooler (9 Bottles)"]       8000.000000
COIRFIT Single Coir Mattress"]                         7307.000000
SJ Comet Zoom DPSI Binoculars (30 mm, Black)"]         6649.000000
Behringer Xenyx 502 Analog Sound Mixer"]               6600.000000
SJ Barstel 56m / 1000m Binoculars (30 mm, Black)"]     6449.000000
Name: discounted_price_₹, dtype: float64

In [36]:
df.groupby('Main_Category')['Discount_Percentage'] \
  .mean() \
  .sort_values(ascending=False) \
  .head(10)

Main_Category
NEWGEN TECH EO-HS3303 218 Wired Headset (White)"]        80.080080
Cellbazaar Blackberry 8520 WHITE LCD LCD (YIT-562)"]     80.000000
Joyra Heart Sterling Silver Swarovski Crystal, S..."]    77.998332
Himmlisch 20503 Car Bottle Holder (Plastic)"]            76.982294
Threads & Pals Full Sleeve Self Design Men's Swe..."]    76.584390
Shonaya Printed Bhagalpuri Art Silk Sari"]               76.282051
Yo Baby Girl's Trousers"]                                76.000000
GALLOWAY skinny Fit Women's Jeans"]                      75.393053
THERISE MD0005 Wired Headset (Pink)"]                    75.075075
Little Stars Girl's A-line Multicolor Dress"]            74.984326
Name: Discount_Percentage, dtype: float64

In [37]:
df['brand'].value_counts().head(15)

brand
unknown         5851
Allure Auto      468
Regular          308
Voylla           299
Slim             284
TheLostPuppy     229
Karatcraft       211
Black            167
White            155
DailyObjects     144
Speedwav         141
Radiant Bay      132
Red              102
Enthopia         101
Pink             100
Name: count, dtype: int64

In [38]:
df['Main_Category'].nunique()

263

In [39]:
df['Main_Category'].value_counts().tail(20)

Main_Category
Autoplus M AP18 Arm Sleeve (Black)"]                     1
Kraft Seeds Thyme Herbs Seed (200 per packet)"]          1
Kraft Seeds Dill Herb Seed (50 per packet)"]             1
Leading lady Women's Camisole"]                          1
Yo Baby Girl's Trousers"]                                1
THERISE MD0005 Wired Headset (Pink)"]                    1
Nut Khut Embroidered Kurta & Churidar"]                  1
Vinenzia Printed Winter Men's Gloves"]                   1
Planet Waves Woodstock Strap (Multicolor)"]              1
Speedwav 216456 Manual Rear View Mirror (Right, ..."]    1
Speedwav 216510 Manual Rear View Mirror (Right, ..."]    1
Speedwav 216552 Manual Rear View Mirror (Right, ..."]    1
Speedwav 186136 Manual Rear View Mirror (Right, ..."]    1
Small Toes Bellies"]                                     1
Clovia Lingerie Set"]                                    1
Speedwav 186926 Royal Enfield 350 Twin Spark LED..."]    1
Speedwav 186879 Bajaj Pulsar 200 NS DTS-i LED In..."]    1
Pazel Slim Fit Men's Jeans"]                             1
SMART TRADERS Girls Bellies"]                            1
Areon Luxurious Fragrance Long Lasting Car,Home,..."]    1
Name: count, dtype: int64

In [40]:
df['product_category_tree'].head(10)

0    ["Clothing >> Women's Clothing >> Lingerie, Sl...
1    ["Furniture >> Living Room Furniture >> Sofa B...
2    ["Footwear >> Women's Footwear >> Ballerinas >...
3    ["Clothing >> Women's Clothing >> Lingerie, Sl...
4    ["Pet Supplies >> Grooming >> Skin & Coat Care...
5    ["Eternal Gandhi Super Series Crystal Paper We...
6    ["Clothing >> Women's Clothing >> Lingerie, Sl...
7    ["Furniture >> Living Room Furniture >> Sofa B...
8    ["Footwear >> Women's Footwear >> Ballerinas >...
9    ["Clothing >> Women's Clothing >> Lingerie, Sl...
Name: product_category_tree, dtype: str

In [41]:
df[df['Main_Category'].str.contains('Asics|Rasav|Behringer|BALAJI', na=False)][
    ['product_category_tree','Main_Category']
].head(10)

,product_category_tree,Main_Category
54,"[""Behringer Xenyx 502 Analog Sound Mixer""]","Behringer Xenyx 502 Analog Sound Mixer""]"
341,"[""Asics Gel-Cumulus 17 Running Shoes""]","Asics Gel-Cumulus 17 Running Shoes""]"
344,"[""Asics Gel-Kayano 22 Running Shoes""]","Asics Gel-Kayano 22 Running Shoes""]"
3297,"[""Rasav Jewels Yellow Gold Diamond 18 K Ring""]","Rasav Jewels Yellow Gold Diamond 18 K Ring""]"
17729,"[""BALAJI EXPORTS Bottled Wine Cooler (9 Bottle...","BALAJI EXPORTS Bottled Wine Cooler (9 Bottles)""]"

In [42]:
df['Main_Category_New'] = (
    df['product_category_tree']
    .str.replace(r'^\["', '', regex=True)
    .str.split('>>')
    .str[0]
    .str.strip()
)

In [43]:
df['Main_Category_New'].nunique()

263

In [44]:
df.Main_Category_New

0            Clothing
1           Furniture
2            Footwear
3            Clothing
4        Pet Supplies
             ...
19995       Baby Care
19996       Baby Care
19997       Baby Care
19998       Baby Care
19999       Baby Care
Name: Main_Category_New, Length: 19922, dtype: object

In [45]:
df['Main_Category_New'].value_counts().tail(20)

Main_Category_New
Autoplus M AP18 Arm Sleeve (Black)"]                     1
Kraft Seeds Thyme Herbs Seed (200 per packet)"]          1
Kraft Seeds Dill Herb Seed (50 per packet)"]             1
Leading lady Women's Camisole"]                          1
Yo Baby Girl's Trousers"]                                1
THERISE MD0005 Wired Headset (Pink)"]                    1
Nut Khut Embroidered Kurta & Churidar"]                  1
Vinenzia Printed Winter Men's Gloves"]                   1
Planet Waves Woodstock Strap (Multicolor)"]              1
Speedwav 216456 Manual Rear View Mirror (Right, ..."]    1
Speedwav 216510 Manual Rear View Mirror (Right, ..."]    1
Speedwav 216552 Manual Rear View Mirror (Right, ..."]    1
Speedwav 186136 Manual Rear View Mirror (Right, ..."]    1
Small Toes Bellies"]                                     1
Clovia Lingerie Set"]                                    1
Speedwav 186926 Royal Enfield 350 Twin Spark LED..."]    1
Speedwav 186879 Bajaj Pulsar 200 NS DTS-i LED In..."]    1
Pazel Slim Fit Men's Jeans"]                             1
SMART TRADERS Girls Bellies"]                            1
Areon Luxurious Fragrance Long Lasting Car,Home,..."]    1
Name: count, dtype: int64

In [46]:
df['Main_Category'].nunique()

263

In [47]:
df['Main_Category_New'].value_counts().head(20)

Main_Category_New
Clothing                      6171
Jewellery                     3522
Footwear                      1225
Mobiles & Accessories         1097
Automotive                    1010
Home Decor & Festive Needs     927
Beauty and Personal Care       709
Home Furnishing                700
Kitchen & Dining               645
Computers                      573
Watches                        528
Baby Care                      481
Tools & Hardware               387
Toys & School Supplies         329
Pens & Stationery              313
Bags, Wallets & Belts          264
Furniture                      180
Sports & Fitness               166
Home Improvement                79
Cameras & Accessories           72
Name: count, dtype: int64

In [50]:
df.columns

Index(['uniq_id', 'crawl_timestamp', 'product_url', 'product_name',
       'product_category_tree', 'pid', 'retail_price_₹', 'discounted_price_₹',
       'Selling Price ₹', 'Discount %', 'is_FK_Advantage_product', 'brand',
       'description', 'product_specifications', 'Main_Category',
       'Price_Segment', 'Discount_Amount', 'Discount_Percentage',
       'Main_Category_New'],
      dtype='str')

In [51]:
df=df.rename(columns={
    'retail_price_₹': 'retail_price',
    'discounted_price_₹': 'discounted_price',
    'Selling Price ₹': 'Selling-price',
    'Discount %': 'discount_percent',
    'Main_Category': 'main_catagory',
    'Price_Segment': 'price_segement',
    'Discount_Amount': 'discount_amaount',
    'Discount_Percentage': 'discount_percentage',
    'Main_Category_New' : 'main_category_new'
})

In [61]:
df.to_csv("python_Flipkart_Cleaned_Data.csv", index=False, encoding='utf-8-sig')

In [56]:
import os
os.path.getsize("Flipkart_Cleaned_Data.csv")

30729144

In [57]:
sql_df=df.drop(columns=[
    'product_url',
    'description',
    'product_specifications',
    'product_category_tree'
])

In [58]:
sql_df.columns

Index(['uniq_id', 'crawl_timestamp', 'product_name', 'pid', 'retail_price',
       'discounted_price', 'Selling-price', 'discount_percent',
       'is_FK_Advantage_product', 'brand', 'main_catagory', 'price_segement',
       'discount_amaount', 'discount_percentage', 'main_category_new'],
      dtype='str')

In [60]:
sql_df.to_csv("SQL_Flipkart_Cleaned_Data.csv", index=False, encoding='utf-8-sig')

In [62]:
sql_df

,uniq_id,crawl_timestamp,product_name,pid,retail_price,discounted_price,Selling-price,discount_percent,is_FK_Advantage_product,brand,main_catagory,price_segement,discount_amaount,discount_percentage,main_category_new
0,c2d766ca982eca8304150849735ffef9,2016-03-25 22:59:23 +0000,Alisha Solid Women's Cycling Shorts,SRTEH2FF9KEDEFGF,999.0,379.0,937.0,62.0,False,Alisha,Clothing,Budget,620.0,62.062062,Clothing
1,7f7036a6d550aaa89d34c77bd39a5e48,2016-03-25 22:59:23 +0000,FabHomeDecor Fabric Double Sofa Bed,SBEEH3QGU7MFYJFY,32157.0,22646.0,32127.0,30.0,False,FabHomeDecor,Furniture,Premium,9511.0,29.576764,Furniture
2,f449ec65dcbc041b6ae5e6a32717d01b,2016-03-25 22:59:23 +0000,AW Bellies,SHOEH4GRSUBJGZXE,999.0,499.0,949.0,50.0,False,AW,Footwear,Budget,500.0,50.050050,Footwear
3,0973b37acd0c664e3de26e97e5571454,2016-03-25 22:59:23 +0000,Alisha Solid Women's Cycling Shorts,SRTEH2F6HUZMQ6SJ,699.0,267.0,637.0,62.0,False,Alisha,Clothing,Budget,432.0,61.802575,Clothing
4,bc940ea42ee6bef5ac7cea3fb5cfbee7,2016-03-25 22:59:23 +0000,Sicons All Purpose Arnica Dog Shampoo,PSOEH3ZYDMSYARJ5,220.0,210.0,215.0,5.0,False,Sicons,Pet Supplies,Budget,10.0,4.545455,Pet Supplies
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,7179d2f6c4ad50a17d014ca1d2815156,2015-12-01 10:15:43 +0000,WallDesign Small Vinyl Sticker,STIE7KFJAKSTDY9G,1500.0,730.0,1449.0,51.0,False,WallDesign,Baby Care,Mid-Range,770.0,51.333333,Baby Care
19996,71ac419198359d37b8fe5e3fffdfee09,2015-12-01 10:15:43 +0000,Wallmantra Large Vinyl Stickers Sticker,STIE9F5URNQGJCGH,1429.0,1143.0,1409.0,20.0,False,Wallmantra,Baby Care,Mid-Range,286.0,20.013996,Baby Care
19997,93e9d343837400ce0d7980874ece471c,2015-12-01 10:15:43 +0000,Elite Collection Medium Acrylic Sticker,STIE7VAYDKQZEBSD,1299.0,999.0,1276.0,23.0,False,Elite Collection,Baby Care,Mid-Range,300.0,23.094688,Baby Care
19998,669e79b8fa5d9ae020841c0c97d5e935,2015-12-01 10:15:43 +0000,Elite Collection Medium Acrylic Sticker,STIE8YSVEPPCZ42Y,1499.0,1199.0,1479.0,20.0,False,Elite Collection,Baby Care,Mid-Range,300.0,20.013342,Baby Care
19999,cb4fa87a874f715fff567f7b7b3be79c,2015-12-01 10:15:43 +0000,Elite Collection Medium Acrylic Sticker,STIE88KN9ZDSGZKY,1499.0,999.0,1466.0,33.0,False,Elite Collection,Baby Care,Mid-Range,500.0,33.355570,Baby Care